# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 594b5931c3cc7970c2d8f1e532748234494ba264900ba3602f359fabb6e201a774c9101a1c7f45d721d543c8471b70d8c4e20312efcd1c272af48b274f88d2a5

test:
  secret_key_base: df415a852ae2c650eefc677718856243def3112fc9e8ac9712b6fd09c813920c627c00f8badbaa7accc7360ac256d793c32be7af70d53b633ee1247fe099c9d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
